version: "3.8"

services:
  pgdb:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=es
      - POSTGRES_USER=djumanov
      - POSTGRES_PASSWORD=djcode

  # pgadmin:
  #   container_name: pgadmin4
  #   image: dpage/pgadmin4
  #   restart: always

  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: a@a.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   ports:
  #     - "5050:80"

  esearch:
    container_name: search
    image: elasticsearch:7.14.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    